// Output screen: archetype scoring and exports
const Output = {
  init() {
    this.screen = document.getElementById('output-screen');
    this.bindFinishButton();
    this.bindBackButton();
    this.bindExports();
  },

  bindFinishButton() {
    document.querySelector('.topbar__finish').addEventListener('click', () => {
      this.show();
    });
  },

  bindBackButton() {
    document.getElementById('output-back-btn').addEventListener('click', () => {
      this.hide();
    });
  },

  show() {
    this.render();
    this.screen.classList.add('output-screen--visible');
    document.querySelector('.app').classList.add('app--hidden');
  },

  hide() {
    this.screen.classList.remove('output-screen--visible');
    document.querySelector('.app').classList.remove('app--hidden');
  },

  render() {
    // 1. Render prompt output
    this.renderPromptPanel();
    // 2. Render SKILL.md output
    this.renderSkillPanel();
    // 3. Score archetype and render card
    this.renderArchetypePanel();
  },

  renderPromptPanel() {
    const container = document.getElementById('output-prompt-content');
    const hasContent = PromptForge.blocks.some(b => b.content && b.content.trim());

    if (!PromptForge.blocks.length || !hasContent) {
      container.innerHTML = '<p class="output-panel__empty">No prompt blocks were filled in. Go back and add some content to your blocks.</p>';
      return;
    }

    // Render styled blocks
    container.innerHTML = PromptForge.blocks.map(b => {
      const content = this.escapeHtml(b.content) || '<em class="output-panel__empty-line">empty</em>';
      return `<div class="output-block" style="--block-color: ${b.color}">
        <span class="output-block__label">${b.label}</span>
        <span class="output-block__content">${content}</span>
      </div>`;
    }).join('');
  },

  renderSkillPanel() {
    const container = document.getElementById('output-skill-content');
    const hasContent = SkillForge.blocks.some(b => b.content && b.content.trim());

    if (!SkillForge.blocks.length || !hasContent) {
      container.innerHTML = '<p class="output-panel__empty">No skill blocks were filled in. Go back and build your SKILL.md.</p>';
      return;
    }

    container.innerHTML = SkillForge.blocks.map(b => {
      const content = this.escapeHtml(b.content) || '<em class="output-panel__empty-line">empty</em>';
      return `<div class="output-block output-block--skill" style="--block-color: ${b.color}">
        <span class="output-block__label">${b.label}</span>
        <span class="output-block__content">${content}</span>
      </div>`;
    }).join('');
  },

  renderArchetypePanel() {
    const archetype = scoreArchetype(PromptForge.blocks);
    const tips = PLAYBOOKS[archetype.id] || [];

    const cardEl = document.getElementById('output-archetype-card');
    cardEl.style.setProperty('--archetype-color', archetype.color);

    cardEl.innerHTML = `
      <div class="archetype-card__badge" style="background: ${archetype.color}">${archetype.title}</div>
      <p class="archetype-card__tagline">${archetype.tagline}</p>
      <p class="archetype-card__description">${archetype.description}</p>
      <div class="archetype-card__playbook">
        <div class="archetype-card__playbook-label">Your Playbook</div>
        ${tips.map(tip => `<div class="archetype-card__tip">${tip}</div>`).join('')}
      </div>
    `;

    // Store for download
    this.currentArchetype = archetype;
    this.currentTips = tips;
  },

  bindExports() {
    // Prompt copy
    document.getElementById('output-prompt-copy').addEventListener('click', () => {
      const text = PromptForge.getRawText();
      if (!text) return;
      navigator.clipboard.writeText(text).then(() => {
        this.flashButton('output-prompt-copy', 'Copied!');
      }).catch(() => {
        this.flashButton('output-prompt-copy', 'Copy failed');
      });
    });

    // SKILL.md download
    document.getElementById('output-skill-download').addEventListener('click', () => {
      const md = SkillForge.getMarkdown();
      if (!md) return;
      const blob = new Blob([`# SKILL.md\n\n${md}`], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'SKILL.md';
      a.click();
      URL.revokeObjectURL(url);
    });

    // Archetype card download (as text)
    document.getElementById('output-card-download').addEventListener('click', () => {
      if (!this.currentArchetype) return;
      const arch = this.currentArchetype;
      const tips = this.currentTips || [];
      const text = [
        `=== ${arch.title} ===`,
        arch.tagline,
        '',
        arch.description,
        '',
        '--- Your Playbook ---',
        ...tips.map((t, i) => `${i + 1}. ${t}`),
        '',
        'Generated by Dual Ground — dualground.app'
      ].join('\n');

      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${arch.id}-personality-card.txt`;
      a.click();
      URL.revokeObjectURL(url);
    });
  },

  flashButton(id, message) {
    const btn = document.getElementById(id);
    const original = btn.textContent;
    btn.textContent = message;
    btn.classList.add('btn--flash');
    setTimeout(() => {
      btn.textContent = original;
      btn.classList.remove('btn--flash');
    }, 1200);
  },

  escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }
};
